name: JuliaPre

on:
  workflow_dispatch:
  # 'pre' currently resolves to 1.12, so no point running it again.
  # This workflow can be reenabled when 'pre' points to 1.13.

  # push:
  #   branches:
  #     - main
  # pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: 'pre' # pre-release
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
